title: "Men Should Read"
description: "Reviews and articles about books and reading"
theme: minima

# optional, but nice:
minima:
  skin: auto

header_pages:
  - reviews.md
  - musings.md
  - about.md
